/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TransactionsObjectPageObjectPage journey");

        opaTest("Navigate to TransactionsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheTransactionsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheTransactionsListGenerated.onTable().iCheckRows();
            When.onTheTransactionsListGenerated.onTable().iPressRow(0);

            Then.onTheTransactionsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the GeneratedFacet1 section of the Object Page", function (_Given, _When, Then) {
            Then.onTheTransactionsObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TransactionID" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DocumentNumber" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Supplier" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProcessType" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProcessingTemplate" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCode" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PostingDate" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Amount" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Currency" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Status" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ValidationIssue" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProcessingAge" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Owner" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Progress" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AutoProcessed" });
            Then.onTheTransactionsObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ApprovalStatus" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});